import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const inter = Raleway({ subsets: ["latin", 'cyrillic'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container px-16">
        <NavBar />
        <main className={`relative overflow-hidden font-normal ${inter.style}`}>{children}</main>
      </body>
    </html>
  );
}
